# Generated by Django 4.2.5 on 2023-09-25 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="wishlists",
            field=models.ManyToManyField(blank=True, related_name="wishlists", to=settings.AUTH_USER_MODEL),
        ),
    ]
