# Generated by Django 4.2.6 on 2023-11-12 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_product_active"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
