# Generated by Django 3.0.3 on 2022-06-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20220627_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
