# Generated by Django 4.2.5 on 2023-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_alter_product_wishlists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
