# Generated by Django 4.1.7 on 2023-08-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_product_category1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category1',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(
                choices=[('fasion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home'),
                         ('others', 'Others')],
                max_length=128,
                null=True
            ),
        ),
        migrations.DeleteModel(name='Category',),
    ]
