# Generated by Django 4.2.5 on 2023-09-20 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0023_product_date_alter_cart_quantity_delete_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="watchlist",
        ),
        migrations.AddField(
            model_name="product",
            name="wishlists",
            field=models.ManyToManyField(blank=True, related_name="wishlists", to=settings.AUTH_USER_MODEL),
        ),
    ]
